name = "run-for"
compatibility_date = "2024-04-01"
compatibility_flags = ["nodejs_compat"]

[[d1_databases]]
binding = "run_for_db"
database_name = "run-for-db"
database_id = "54b87715-9cd0-473a-ac88-b8ce1ede1222"
migrations_dir = "drizzle"
